### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by osrf-migration** [ignitionrobotics/ign-physics#9]
**Original report ([archived issue](https://osrf-migration.github.io/ignition-gh-pages/#!/ignitionrobotics/ign-physics/issues/9)) by Louise Poubel (Bitbucket: [chapulina](https://bitbucket.org/%7B5cfa2075-477b-4ded-bdb9-8d2479544ec4%7D/), GitHub: [chapulina](https://github.com/chapulina)).**

----------------------------------------
# Summary

A lot of the API (most of it?) is not documented, so downstream developers need to come dig through the code to find out what functions are supposed to be doing.

For example,  what does [ConstructCollision](https://github.com/ignitionrobotics/ign-physics/blob/a99c99d267972afee4501c061e31dd9821fb131d/sdf/include/ignition/physics/sdf/ConstructCollision.hh#L36) do? Does it create **and** attach a collision to a link? How is that different from [AttachMeshShape](https://github.com/ignitionrobotics/ign-physics/blob/a99c99d267972afee4501c061e31dd9821fb131d/mesh/include/ignition/physics/mesh/MeshShape.hh#L106)? If they do similar things, why are their names so different?

# Motivation

It's difficult for downstream developers to use the API if it's not clear what it does.

# Describe alternatives you've considered

Forcing everyone to dig through the code or test the API by trial and error? :grimacing:

# Additional context

Documentation is love :heart_decoration:

**Comment by claireyywang** [comment]
@anindex Since there is already an issue, I will just tag along here. 

List of `ign-physics` classes that need documentation https://ignitionrobotics.org/api/physics/3.1/annotated.html
To add documentation to doxygen, click on the class name on the API page above to see the relavant source code file name. 

- [ ] AttachBoxShapeFeature
- [ ] AttachCylinderShapeFeature
- [ ] AttachPlaneShapeFeature
- [ ] AttachSphereShapeFeature
- [ ] ConstructEmptyLinkFeature
- [ ] ConstructEmptyModelFeature
- [ ] ConstructEmptyWorldFeature
- [ ] GetBasicJointProperties
- [ ] GetBasicJointState
- [ ] GetEngineInfo
- [ ] GetJointFromModel
- [ ] GetLinkBoundingBox 
- [ ] GetLinkFromModel 
- [ ] GetModelBoundingBox 
- [ ] GetModelFromWorld 
- [ ] GetShapeBoundingBox 
- [ ] GetShapeCollisionProperties 
- [ ] GetShapeFrictionPyramidSlipCompliance 
- [ ] GetShapeFromLink 
- [ ] GetShapeKinematicProperties 
- [ ] GetWorldFromEngine
- [ ] RemoveModelFromWorld
- [ ] SetBasicJointState
- [ ] SetCylinderShapeProperties 
- [ ] SetFreeGroupWorldPose 
- [ ] SetFreeGroupWorldVelocity
- [ ] SetJointVelocityCommandFeature
- [ ] SetShapeCollisionProperties
- [ ] SetShapeFrictionPyramidSlipCompliance

**Comment by claireyywang** [comment]
closing since all PRs are merged
